import os
import sys
import json
import argparse
import logging
from pathlib import Path
from ultralytics import YOLO

# Set UTF-8 output encoding for Windows compatibility
if sys.stdout.encoding != 'utf-8':
    try:
        sys.stdout.reconfigure(encoding='utf-8')
    except AttributeError:
        pass

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("TrainYOLO")


def generate_metrics_report(model, val_results, dataset_path: str, base_model: str, epochs: int, report_path: str = "data/training_report.md"):
    """
    Extract evaluation metrics from validation results and generate a structured markdown report.
    """
    box_metrics = val_results.box

    mp = float(box_metrics.mp) if hasattr(box_metrics, 'mp') else 0.0
    mr = float(box_metrics.mr) if hasattr(box_metrics, 'mr') else 0.0
    map50 = float(box_metrics.map50) if hasattr(box_metrics, 'map50') else 0.0
    map50_95 = float(box_metrics.map) if hasattr(box_metrics, 'map') else 0.0

    class_maps = {}
    if hasattr(box_metrics, 'maps') and box_metrics.maps is not None:
        for idx, map_val in enumerate(box_metrics.maps):
            cls_name = model.names.get(idx, f"Class_{idx}")
            class_maps[cls_name] = float(map_val)

    report_content = f"""# 🚀 YOLOv8 Fire & Smoke Model Training Report

## 📌 Executive Summary
- **Base Architecture**: `{base_model}`
- **Dataset Configuration**: `{dataset_path}`
- **Epochs Trained**: `{epochs}`
- **Evaluation Status**: Successfully completed validation.

---

## 📊 Key Evaluation Metrics

| Metric | Score | Description |
| :--- | :---: | :--- |
| **Precision (P)** | **{mp:.4f}** ({mp*100:.1f}%) | Ratio of correct positive predictions |
| **Recall (R)** | **{mr:.4f}** ({mr*100:.1f}%) | Ratio of actual hazards detected |
| **mAP@50** | **{map50:.4f}** ({map50*100:.1f}%) | Mean Average Precision at IoU=0.50 |
| **mAP@50-95** | **{map50_95:.4f}** ({map50_95*100:.1f}%) | Mean Average Precision across IoU 0.50:0.95 |

---

## 🏷️ Per-Class Performance (mAP@50-95)

| Class ID | Class Name | mAP@50-95 |
| :---: | :--- | :---: |
"""
    for idx, (cls_name, map_val) in enumerate(class_maps.items()):
        report_content += f"| {idx} | **{cls_name}** | {map_val:.4f} ({map_val*100:.1f}%) |\n"

    report_content += f"""
---

## 📁 Training Artifacts
- **Model Checkpoints**: Saved under `runs/train/`
- **Best Weights**: `runs/train/fire_smoke_yolov8s/weights/best.pt`
- **Last Weights**: `runs/train/fire_smoke_yolov8s/weights/last.pt`

*Report auto-generated by `src/train/train.py`.*
"""

    os.makedirs(os.path.dirname(report_path), exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(report_content)

    print("\n==========================================")
    print("      TRAINING METRICS REPORT SUMMARY")
    print("==========================================")
    print(f"  • Base Model:   {base_model}")
    print(f"  • Precision:    {mp:.4f} ({mp*100:.1f}%)")
    print(f"  • Recall:       {mr:.4f} ({mr*100:.1f}%)")
    print(f"  • mAP@50:       {map50:.4f} ({map50*100:.1f}%)")
    print(f"  • mAP@50-95:    {map50_95:.4f} ({map50_95*100:.1f}%)")
    print("==========================================")
    print(f"Full report saved to: {report_path}\n")

    return report_content


def train_fire_smoke_model(
    data_yaml: str,
    base_model: str = "yolov8s.pt",
    epochs: int = 5,
    imgsz: int = 640,
    batch: int = 16,
    project: str = "runs/train",
    name: str = "fire_smoke_yolov8s",
    # Data Augmentation parameters
    hsv_h: float = 0.015,
    hsv_s: float = 0.7,
    hsv_v: float = 0.4,
    degrees: float = 10.0,
    translate: float = 0.1,
    scale: float = 0.5,
    shear: float = 2.0,
    fliplr: float = 0.5,
    mosaic: float = 1.0,
    mixup: float = 0.15,
    copy_paste: float = 0.1,
    report_path: str = "data/training_report.md"
):
    """
    Train YOLOv8 model for Fire & Smoke detection and generate evaluation report.
    """
    logger.info(f"Loading base YOLOv8 model: {base_model}")
    model = YOLO(base_model)

    logger.info(f"Starting training for {epochs} epochs on {data_yaml}...")

    # Train model
    results = model.train(
        data=data_yaml,
        epochs=epochs,
        imgsz=imgsz,
        batch=batch,
        project=project,
        name=name,
        plots=True,
        hsv_h=hsv_h,
        hsv_s=hsv_s,
        hsv_v=hsv_v,
        degrees=degrees,
        translate=translate,
        scale=scale,
        shear=shear,
        fliplr=fliplr,
        mosaic=mosaic,
        mixup=mixup,
        copy_paste=copy_paste
    )

    logger.info("Training finished. Running validation to evaluate precision, recall, and mAP...")
    val_results = model.val()

    # Generate metrics report
    generate_metrics_report(
        model=model,
        val_results=val_results,
        dataset_path=data_yaml,
        base_model=base_model,
        epochs=epochs,
        report_path=report_path
    )

    return results


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Train YOLOv8 Fire & Smoke Detector and Save Metrics Report")
    parser.add_argument("--data", type=str, default="data/processed/data.yaml", help="Path to dataset yaml")
    parser.add_argument("--model", type=str, default="yolov8s.pt", help="Base model weights (yolov8s.pt or yolov8m.pt)")
    parser.add_argument("--epochs", type=int, default=5, help="Number of training epochs")
    parser.add_argument("--batch", type=int, default=16, help="Batch size")
    parser.add_argument("--imgsz", type=int, default=640, help="Image size")

    args = parser.parse_args()

    data_path = args.data
    if not Path(data_path).exists():
        data_path = "data/raw/data.yaml"

    train_fire_smoke_model(
        data_yaml=data_path,
        base_model=args.model,
        epochs=args.epochs,
        imgsz=args.imgsz,
        batch=args.batch
    )
